### ISSUE TITLE
Fix false negatives in automated tests

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/ally.js#56]
When running the test suite against BrowserStack I get the following failures. Things are working fine in local tests (running the browser client in a local VM) and when running the demos from the docs. I'm not sure how to handle these discrepancies. I assume this has something to do with Intern / LeadFoot / WebDriver / BrowserStack.

```
× IE10 on WIN - unit tests - get/focus-target - none (body) (0.002s)
AssertionError: expected <div id="intern-dom-fixture"> to equal null

× IE10 on WIN - unit tests - query/focusable.all - document (0.085s)
AssertionError: expected 'div, div, #intern-dom-fixture, <…>' to equal '<…>'

× IE10 on WIN - unit tests - query/focusable.strict - document (0.151s)
AssertionError: expected 'div, div, div, #intern-dom-fixture, <…>' to equal '<…>'
```

I guess the unexpected `<div>` elements are scrollable and thus considered focusable - I have no idea why this is happening, though.

---

```
× IE10 on WIN - unit tests - event/active-element - lifecycle (0.29s)
CancelError: Timeout reached on IE10 on WIN - unit tests - event/active-element - lifecycle
  at Anonymous function  <__intern/lib/Test.js:242:9>
  at cancel  <__intern/node_modules/dojo/Promise.js:120:21>
  at Anonymous function  <__intern/lib/Test.js:164:7>

× IE10 on WIN - unit tests - style/focus-source - lifecycle (0.185s)
CancelError: Timeout reached on IE10 on WIN - unit tests - style/focus-source - lifecycle
  at Anonymous function  <__intern/lib/Test.js:242:9>
  at cancel  <__intern/node_modules/dojo/Promise.js:120:21>
  at Anonymous function  <__intern/lib/Test.js:164:7>

× IE10 on WIN - unit tests - style/focus-source - key (0.888s)
CancelError: Timeout reached on IE10 on WIN - unit tests - style/focus-source - key
  at Anonymous function  <__intern/lib/Test.js:242:9>
  at cancel  <__intern/node_modules/dojo/Promise.js:120:21>
  at Anonymous function  <__intern/lib/Test.js:164:7>

× IE10 on WIN - unit tests - style/focus-source - pointer (0.274s)
CancelError: Timeout reached on IE10 on WIN - unit tests - style/focus-source - pointer
  at Anonymous function  <__intern/lib/Test.js:97:5>
  at cancel  <__intern/node_modules/dojo/Promise.js:120:21>
  at Anonymous function  <__intern/lib/Test.js:234:10>
  at cancel  <__intern/node_modules/dojo/Promise.js:120:21>
  at Anonymous function  <__intern/lib/Test.js:164:7>
```

and

```
× IE11 on WIN - unit tests - observe/interaction-type - detect mouse (0.098s)
CancelError: Timeout reached on IE11 on WIN - unit tests - observe/interaction-type - detect mouse
  at Anonymous function  <__intern/lib/Test.js:242:9>
  at cancel  <__intern/node_modules/dojo/Promise.js:120:21>
  at Anonymous function  <__intern/lib/Test.js:164:7>
```

I'm not sure how `setTimeout(…, 20);` can possibly hit a 100ms timeout.

---

```
× Firefox 40 on WIN - unit tests - when/focusable - scroll parent, area: 1 (0.742s)
CancelError: Timeout reached on Firefox 40 on WIN - unit tests - when/focusable - scroll parent, area: 1
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:162:20>

× Firefox 40 on WIN - unit tests - when/focusable - scroll parent, area: 0.5 (1.46s)
CancelError: Timeout reached on Firefox 40 on WIN - unit tests - when/focusable - scroll parent, area: 0.5
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:162:20>

× Firefox 40 on WIN - unit tests - when/visible-area - repeat callback (0.502s)
CancelError: Timeout reached on Firefox 40 on WIN - unit tests - when/visible-area - repeat callback
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:162:20>
```

Maybe the container's size changes so that the calculations are off by a (few) pixels?

---

Upgrading a few timeouts and updating to the latest version of Firefox available on BrowserStack seems to have reduced the problems. Or maybe it was running the tests repeatedly. Or the moon's ascent. Or whatever. Who knows… Fact is, a few tests keep failing on Intern that don't fail when run locally.

**Comment by rodneyrehm** [comment]
right, the tests aren't flaky at all…

* Build 10: https://travis-ci.org/medialize/ally.js/builds/91569028#L1060 
* Build 10: https://travis-ci.org/medialize/ally.js/builds/91569028#L1080
* Build 11: https://travis-ci.org/medialize/ally.js/builds/91581091#L1532
* Build 12: https://travis-ci.org/medialize/ally.js/builds/91658490#L1600
* Build 12: https://travis-ci.org/medialize/ally.js/builds/91658490#L1716

Travis will continue to build (i.e. run `npm run ci:test`) on every push, even though the result (i.e. build failed) won't say much about anything…

**Comment by rodneyrehm** [comment]
let's see what the experts say, theintern/intern#539

**Comment by rodneyrehm** [comment]
after bumping the timeouts to (ridiculous) 10 seconds the [builds seem to have stablizied](https://travis-ci.org/medialize/ally.js/builds)… :dancers:
